import FlagsProvider from "@/components/flags-provider";
import {
  flagConfetti,
  flagLightTheme,
  flagShowNotes,
  precomputedFlags,
} from "@/lib/flags";
import { VercelToolbar } from "@vercel/toolbar/next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tomas' Presentations",
  description: "Presentations generated by Tomas Jansson",
};
// import { FlagValues } from "flags/react";
// import { encryptFlagValues, FlagValuesType } from "flags";
import Script from "next/script";
import { Confetti } from "@/components/confetti";

// async function ConfidentialFlagValues({ values }: { values: FlagValuesType }) {
//   const encryptedFlagValues = await encryptFlagValues(values);
//   return <FlagValues values={encryptedFlagValues} />;
// }

const Ahrefs = () => {
  return (
    <>
      <Script
        src="https://analytics.ahrefs.com/analytics.js"
        data-key="rsgznZxou1mRnnm5co/egg"
        async
      ></Script>
    </>
  );
};

const GooleVerification = () => {
  return (
    <>
      <meta
        name="google-site-verification"
        content="4MPryxTfeXv58y_a9eoHejRiMj4yeWiRkGxCXnibBsc"
      />
    </>
  );
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ code: string }>;
}) {
  const { code } = await params;
  console.log("==> LAYOUT CODE: ", code);
  const showNotes = await flagShowNotes(code, precomputedFlags);
  const lightTheme = await flagLightTheme(code, precomputedFlags);
  const confetti = await flagConfetti(code, precomputedFlags);
  console.log("==> FLAGS: ", { showNotes, lightTheme, confetti });
  const isDevelopment = process.env.NODE_ENV === "development";
  return (
    <html lang="en" className={lightTheme ? "light" : "dark"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground h-screen w-screen`}
      >
        <FlagsProvider flags={{ showNotes }}>
          {children}
          <div className="z-index-50">{isDevelopment && <VercelToolbar />}</div>
        </FlagsProvider>
        {/* <ConfidentialFlagValues
          values={{ "show-notes": showNotes, "light-theme": lightTheme }}
        /> */}
        <Ahrefs />
        <GooleVerification />
        {confetti && <Confetti />}
      </body>
    </html>
  );
}
